import type { City, FinishedDay, GraphNode, Hood, Place, PlaceEntry, PlaceInfo, PlaceMedia, StartLoc } from '../types'
import cityJson from './data/city.json'
import placesJson from './data/places.json'
import infoJson from './data/info.json'
import entryJson from './data/entry.json'
import nodesJson from './data/nodes.json'
import hoodsJson from './data/hoods.json'
import curatedDaysJson from './data/curated-days.json'
import mediaJson from './data/media.json'
/**
 * slot-files.json matches the archive drop in public/media/paris/ to the
 * interface's slots, by content. Original filenames are kept — this map is
 * the join. Slots not listed keep their placeholders: a placeholder is more
 * honest than a photo of the wrong place. `_gen-*` files are derived (video
 * stills / H.264 web conversions) via ffmpeg — regenerate freely, never edit.
 */
import slotFilesJson from './data/slot-files.json'
/** media-dates.json is generated by scripts/extract-dates.sh — do not edit. */
import mediaDatesJson from './data/media-dates.json'

/* JSON widens tuples and string unions, so the data is asserted back to the
 * `City` contracts here. `npm run validate:cities` is the real guarantee —
 * it checks every field, range and cross-reference the types can't. */
export const PARIS: City = {
  ...(cityJson as unknown as Omit<City, 'places' | 'info' | 'entry' | 'nodes' | 'hoods' | 'curatedDays' | 'media' | 'slotFiles' | 'mediaDates'> & { start: StartLoc }),
  places: placesJson as unknown as Place[],
  info: infoJson as Record<string, PlaceInfo>,
  entry: entryJson as Record<string, PlaceEntry>,
  nodes: nodesJson as unknown as GraphNode[],
  hoods: hoodsJson as Hood[],
  curatedDays: curatedDaysJson as unknown as FinishedDay[],
  media: mediaJson as unknown as Record<string, PlaceMedia>,
  slotFiles: slotFilesJson as Record<string, { img?: string; video?: string }>,
  mediaDates: mediaDatesJson as Record<string, string>,
}
